install routing rules only when processing a lease for that protocol
Split the rewrite_rules function into protocol specific variants (IPv4
and IPv6) and call the appropriate variant for the lease being
processed. In other words, don't try to manipulate IPv6 routing rules
when processing an IPv4 DHCP lease, and vice-versa.

diff --git a/ec2net-functions b/ec2net-functions
--- a/ec2net-functions
+++ b/ec2net-functions
@@ -331,7 +331,53 @@ remove_rules() {
   done
 }
 
-rewrite_rules() {
+rewrite_rules_v6() {
+  if [ "${INTERFACE}" == "eth0" ]; then
+    return
+  fi
+
+  ip6s=($(get_ipv6s))
+  if [ $? -gt 0 ]; then
+    # If we get an error fetching the list of IPs from IMDS,
+    # bail out early.
+    logger --tag ec2net "[rewrite_rules] Could not get IPv6 addresses for ${INTERFACE} from IMDS. Aborting"
+    return
+  fi
+  ip6s+=($(get_delegated_prefix ipv6))
+
+  # This is the part we would do in rewrite_primary() if we knew
+  # the gateway address.
+  if [ ${#ip6s[*]} -gt 0 -a -z "$(ip -6 route show table ${RTABLE})" ]; then
+    gateway6=$(get_ipv6_gateway)
+    # Manually add the route, then add it to ${route6_file} so it
+    # gets brought down with the rest of the interface.
+    ip -6 route add default via ${gateway6} dev ${INTERFACE} table ${RTABLE}
+    cat <<- EOF > ${route6_file}
+	default via ${gateway6} dev ${INTERFACE} table ${RTABLE}
+EOF
+  fi
+
+  declare -A rules6
+  for rule in $(ip -6 rule list \
+                    |grep "from .* lookup ${RTABLE}" \
+                    |awk '{print $1$3}'); do
+      split=(${rule/:/ }) # take care to only replace the first :
+      rules6[${split[1]}]=${split[0]}
+  done
+  for ip in "${ip6s[@]}"; do
+      if [[ ${rules6[${ip}]} ]]; then
+          unset rules6[${ip}]
+      else
+          ip -6 rule add from ${ip} lookup ${RTABLE}
+      fi
+  done
+  for rule in "${!rules6[@]}"; do
+      ip -6 rule delete pref "${rules6[${rule}]}"
+  done
+
+}
+
+rewrite_rules_v4() {
   if [ "${INTERFACE}" == "eth0" ]; then
     return
   fi
@@ -345,29 +391,9 @@ rewrite_rules() {
   fi
   ips+=($(get_delegated_prefix ipv4))
 
-  ip6s=($(get_ipv6s))
-  if [ $? -gt 0 ]; then
-    # If we get an error fetching the list of IPs from IMDS,
-    # bail out early.
-    logger --tag ec2net "[rewrite_rules] Could not get IPv6 addresses for ${INTERFACE} from IMDS. Aborting"
-    return
-  fi
-  ip6s+=($(get_delegated_prefix ipv6))
-
   if [ ${#ips[*]} -eq 0 ]; then
     remove_rules
     return
-  fi
-  # This is the part we would do in rewrite_primary() if we knew
-  # the gateway address.
-  if [ ${#ip6s[*]} -gt 0 -a -z "$(ip -6 route show table ${RTABLE})" ]; then
-    gateway6=$(get_ipv6_gateway)
-    # Manually add the route, then add it to ${route6_file} so it
-    # gets brought down with the rest of the interface.
-    ip -6 route add default via ${gateway6} dev ${INTERFACE} table ${RTABLE}
-    cat <<- EOF > ${route6_file}
-	default via ${gateway6} dev ${INTERFACE} table ${RTABLE}
-EOF
   fi
   logger --tag ec2net "[rewrite_rules] Rewriting rules for ${INTERFACE}"
   # Retrieve a list of IP rules for the route table that belongs
@@ -393,24 +419,24 @@ EOF
   for rule in "${!rules[@]}"; do
     ip -4 rule delete pref "${rules[${rule}]}"
   done
-  # Now do the same, but for IPv6
-  declare -A rules6
-  for rule in $(ip -6 rule list \
-                |grep "from .* lookup ${RTABLE}" \
-                |awk '{print $1$3}'); do
-    split=(${rule/:/ }) # take care to only replace the first :
-    rules6[${split[1]}]=${split[0]}
-  done
-  for ip in "${ip6s[@]}"; do
-    if [[ ${rules6[${ip}]} ]]; then
-      unset rules6[${ip}]
-    else
-      ip -6 rule add from ${ip} lookup ${RTABLE}
-    fi
-  done
-  for rule in "${!rules6[@]}"; do
-    ip -6 rule delete pref "${rules6[${rule}]}"
-  done
+}
+
+rewrite_rules() {
+    # export by dhclient:
+    local reason=$reason
+    case "$reason" in
+        "")
+            logger --tag ec2net "rewrite_rules called with no reason"
+            return 1
+            ;;
+        BOUND|RENEW|REBOOT)
+            rewrite_rules_v4
+            ;;
+        BOUND6|RENEW6|REBIND6)
+            rewrite_rules_v6
+            ;;
+    esac
+    return 0
 }
 
 plug_interface() {
